Repository Alfresco/alfresco-build-tools, pull requests merged in 2021-04, with the labels that each got.

#9 Show diff on pre-commit failure
  .travis.pre-commit.yml
Labels: PR: unreviewed

#10 AAE-4984 Add snippet to authenticate on docker hub
  .travis.docker_hub_login.yml
Labels: PR: reviewed-approved

#11 AAE-5058 Allow new starter artifacts to be published in nexus
  .travis.maven_config.yml
Labels: PR: partially-approved
