Repository Alfresco/alfresco-build-tools, pull requests merged in 2022-09, with the labels that each got.

#104 AAE-10134: turn dependabot and version propagation GH reusable workfl…
  .github/actions/automate-dependabot/action.yml
  .github/actions/automate-propagation/action.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/versions-propagation-auto-merge.yml
  README.md
Labels: PR: unreviewed

#115 Release v1.13.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#106 OPSEXP-1545 Decrease duplication in build scripts for helm charts with github custom actions
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/publish-chart/publish_chart.sh
  .github/actions/dbp-charts/verify-compose/action.yml
  .github/actions/dbp-charts/verify-compose/docker_compose.sh
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/dbp-charts/verify-helm/helm_install.sh
Labels: PR: draft, PR: partially-approved

#117 Release v1.14.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#118 OPSEXP-1718 Debug with ssh action
  README.md
Labels: PR: partially-approved

#119 AAE-8916 Add the possibility to specify the type of the prerelease
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/calculate-next-internal-version/next-prerelease.sh
Labels: PR: unreviewed

#121 Add travis snippet to configure git author
  .travis.git_config.yml
  .travis.yml
  README.md
Labels: PR: unreviewed

#122 Release v1.15.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#120 OPSEXP-1545 Scripts refactoring
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/publish-chart/publish_chart.sh
  .github/actions/dbp-charts/verify-compose/action.yml
  .github/actions/dbp-charts/verify-compose/docker_compose.sh
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/dbp-charts/verify-helm/helm_install.sh
Labels: PR: reviewed-approved

#123 OPSEXP-1545 Fix compose tests for forked PRs
  .github/actions/dbp-charts/verify-compose/action.yml
Labels: PR: reviewed-approved

#124 OPSEXP-1735 permit disabling autogenerated pom upload for maven deploy file
  .github/actions/maven-deploy-file/action.yml
Labels: PR: reviewed-approved

#127 make docker hub creds and file optional
  .github/actions/dbp-charts/verify-compose/action.yml
Labels: PR: reviewed-approved

#128 OPSEXP-1746: allow passing additional args to pre-commit
  .github/actions/pre-commit/action.yml
Labels: PR: partially-approved

#129 OPSEXP-1746: fix broken pre-commit action
  .github/actions/pre-commit/action.yml
Labels: PR: reviewed-approved

#130 AAE-8916 Add action to update project base tag in release descriptor
  .github/actions/update-project-base-tag/action.yml
  README.md
Labels: PR: partially-approved

#131 OPSEXP-1746: add an helm-unittest action
  .github/actions/helm-unit-tests/action.yml
  README.md
Labels: PR: partially-approved

#132 Release v1.16.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved
