Repository Alfresco/alfresco-build-tools, pull requests merged in 2022-03, with the labels that each got.

#19 fix: AAE-7879 use semver to calculate next prerelease
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/calculate-next-internal-version/next-prerelease.sh
Labels: PR: partially-approved

#23 Bump helm from 3.8.0 to 3.8.1
  .pre-commit-hooks.yaml
  .travis.helm_install.yml
  .travis.yml
Labels: PR: unreviewed

#24 Bump kubernetes from 1.21.7 to 1.21.10
  .travis.kubernetes_install.yml
  .travis.yml
Labels: PR: unreviewed

#25 Add docker-buildx Travis CI install
  .travis.docker-buildx_install.yml
  .travis.yml
Labels: PR: unreviewed

#26 OPSEXP-1357 Add helm-install action
  .github/actions/setup-helm/action.yml
  .github/actions/setup-helm/setup-helm.sh
  .github/workflows/test.yml
  README.md
Labels: PR: reviewed-approved

#32 OPSEXP-1357 Add setup kubepug action
  .github/actions/setup-kubepug/action.yml
  .github/actions/setup-kubepug/setup-kubepug.sh
  .github/workflows/test.yml
Labels: PR: reviewed-approved

#33 OPSEXP-1357 add placeholders in readme for further extension
  README.md
Labels: PR: unreviewed

#34 OPSEXP-1357 Add migrate to actions table in README
  README.md
Labels: PR: partially-approved

#35 [minor] Link official migrate from travis of github docs in README
  README.md
Labels: PR: reviewed-approved

#28 OPSEXP-1358 Add pre-commit action
  .github/actions/pre-commit/action.yml
  .github/workflows/test.yml
  README.md
Labels: PR: partially-approved
