Repository Alfresco/alfresco-build-tools, pull requests merged in 2022-04, with the labels that each got.

#37 Document usage of docker build action for buildx support
  README.md
Labels: PR: reviewed-approved

#36 Document replacement action for auto cancel builds
  README.md
Labels: PR: reviewed-approved

#42 Bump helm-docs from 1.7.0 to 1.8.1
  .github/actions/setup-helm-docs/action.yml
  .travis.helm-docs_install.yml
Labels: PR: unreviewed

#43 Bump yq from version `4.6.1` to `4.24.4`
  .github/actions/setup-yq/action.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#40 Suggest more maintained action for auto cancel branch builds
  README.md
Labels: PR: reviewed-approved

#39 Suggest specific action for buildx support
  README.md
Labels: PR: reviewed-approved

#44 Add tip about missing realpath on macosx
  README.md
Labels: PR: partially-approved

#46 OPSEXP-1385 Remove existing setup helm action as tool is preinstalled
  .github/actions/setup-helm/action.yml
  .github/actions/setup-helm/setup-helm.sh
  .github/workflows/test.yml
  README.md
Labels: PR: reviewed-approved

#48 Bump tflint from 0.34.1 to 0.35.0
  .travis.tflint_install.yml
Labels: PR: unreviewed

#49 Bump kubectl from 1.21.10 to 1.23.5
  .travis.kubernetes_install.yml
Labels: PR: unreviewed

#50 Bump helm-docs from 1.8.1 to 1.9.1
  .github/actions/setup-helm-docs/action.yml
  .travis.helm-docs_install.yml
Labels: PR: unreviewed

#51 Bump terraform from 1.1.5 to 1.1.9
  .travis.terraform_install.yml
  .travis.yml
Labels: PR: unreviewed

#52 Bump checkov from 2.0.930 to 2.0.1080
  .github/actions/setup-checkov/action.yml
  .travis.checkov_install.yml
  .travis.yml
Labels: PR: unreviewed

#53 Bump yq from 4.24.4 to 4.25.1
  .github/actions/setup-yq/action.yml
  .travis.yml
  .travis.yq_install.yml
Labels: PR: unreviewed
