Repository Alfresco/alfresco-build-tools, pull requests merged in 2022-07, with the labels that each got.

#79 AAE-8962 fix build for Veracode
  .github/workflows/publish-artifacts-for-veracode.yml
Labels: PR: partially-approved

#81 AAE-9367 handle auto merge of propagation PRs
  .github/workflows/versions-propagation-auto-merge.yml
Labels: PR: partially-approved

#80 Make sure that origin is updated when doing a release
  release.sh
Labels: PR: unreviewed

#82 Release v1.8.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-chart-version/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: unreviewed

#84 AAE-9367 fix condition for auto-merge
  .github/workflows/versions-propagation-auto-merge.yml
Labels: PR: partially-approved

#85 AAE-9448: allow adding maven options in java build
  .github/workflows/build-and-tag-maven.yml
Labels: PR: unreviewed

#87 AAE-8814: add action to auto-merge dependabot minor and patch PRs
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/versions-propagation-auto-merge.yml
  README.md
Labels: PR: reviewed-approved

#89 AAE-9076: add action to send slack notification
  .github/actions/send-slack-notification/action.yml
  README.md
Labels: PR: unreviewed

#90 Release v1.9.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-chart-version/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#91 AAE-9490: fix release script for linux
  release.sh
Labels: PR: partially-approved

#93 AAE-8814: fix issues for dependabot PRs management
  .github/workflows/build-and-tag-maven.yml
Labels: PR: partially-approved

#94 Release v1.9.1
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-chart-version/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#95 OPSEXP-1387: Replace existing setup checkov action with bridgecrewio/checkov-action
  .github/actions/setup-checkov/action.yml
  .github/workflows/test.yml
  README.md
Labels: PR: partially-approved

#96 AAE-10027: echo 20 longest tests run
  .github/workflows/build-and-tag-maven.yml
Labels: PR: partially-approved

#97 add custom message support and special case for issues
  .github/actions/send-slack-notification/action.yml
Labels: PR: partially-approved

#98 Release v1.9.2
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-chart-version/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/helm-publish-new-package-version.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#99 AAE-10094: document pre-commit update when migrating to Github Actions
  README.md
Labels: PR: reviewed-approved

#100 AAE-10163: configure dependabot for GH actions
  .github/dependabot.yml
Labels: PR: partially-approved
