Repository Alfresco/alfresco-build-tools, pull requests merged in 2022-05, with the labels that each got.

#55 Bump awscli from 2.4.25 to 2.6.1
  .travis.awscli_install.yml
  .travis.yml
Labels: PR: unreviewed

#56 Bump checkov from 2.0.1080 to 2.0.1095
  .travis.checkov_install.yml
Labels: PR: unreviewed

#54 Add community action for retrying commands
  README.md
Labels: PR: reviewed-approved

#58 Bump awscli from 2.6.1 to 2.7.0
  .travis.awscli_install.yml
Labels: PR: unreviewed

#59 Add information about security
  README.md
Labels: PR: unreviewed

#61 OPSEXP-1448 add setup-github-release-binary action
  .github/actions/setup-github-release-binary/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .pre-commit-config.yaml
  README.md
Labels: PR: unreviewed

#63 Remove unneeded setup-yq action
  .github/actions/setup-yq/action.yml
  .github/workflows/test.yml
  README.md
Labels: PR: unreviewed

#64 Bump helm-docs from 1.9.1 to 1.10.0
  .github/actions/setup-helm-docs/action.yml
  .travis.helm-docs_install.yml
Labels: PR: unreviewed

#65 Add setup-kcadm action
  .github/actions/setup-kcadm/action.yml
  .github/workflows/test.yml
  .travis.kcadm_install.yml
  .travis.yml
Labels: PR: unreviewed

#66 Bump awscli from 2.7.0 to 2.7.2
  .travis.awscli_install.yml
Labels: PR: unreviewed

#57 Add community actions for java, workflow dispatch and slack notifs
  README.md
Labels: PR: partially-approved

#60 AAE-8518 add utility GH Actions/workflows to build helm projects
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/git-commit-changes/action.yml
  .github/actions/package-helm-chart/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/shared-scripts/get-current-action-branch.sh
  .github/actions/update-chart-version/action.yml
  .github/workflows/helm-publish-new-package-version.yml
  README.md
Labels: PR: partially-approved

#69 [minor] Fixup codacy issues
  README.md
Labels: PR: reviewed-approved
