Repository Alfresco/alfresco-build-tools, pull requests merged in 2022-10, with the labels that each got.

#133 Fixup deploy-file when deploying a single file
  .github/actions/maven-deploy-file/action.yml
Labels: PR: unreviewed

#105 AAE-10135: turn build-and-tag-maven GH reusable workflow into an acti…
  .github/actions/maven-build-and-tag/action.yml
  .github/workflows/build-and-tag-maven.yml
  README.md
Labels: PR: partially-approved

#135 Release v1.17.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#136 OPSEXP-1746: helm skip co
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/dbp-charts/verify-helm/helm_install.sh
Labels: PR: partially-approved

#138 Add pr label conditionals in cookbook section
  README.md
Labels: PR: partially-approved

#139 Add paragraph about enabling back build output
  README.md
Labels: PR: reviewed-approved

#137 fix(AAE-10901): add jx-updatebot-pr Github Action
  .github/actions/jx-updatebot-pr/action.yml
  README.md
Labels: PR: partially-approved

#140 enable markdownlint pre-commit hook
  .markdownlint.yml
  .pre-commit-config.yaml
  README.md
Labels: PR: reviewed-approved

#142 Fix 'travis-env-load' example
  README.md
Labels: PR: reviewed-approved

#145 Release v1.18.0
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#144 OPSEXP-1777 Fixup verify-helm action
  .github/actions/dbp-charts/verify-helm/helm_install.sh
Labels: PR: reviewed-approved

#147 AAE-10961: improve maven cache logic
  .github/actions/maven-build-and-tag/action.yml
Labels: PR: reviewed-approved

#148 Release v1.18.1
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#149 OPSEXP-1772 Migrate to new way to set outputs in our actions
  .github/actions/automate-dependabot/action.yml
  .github/actions/automate-propagation/action.yml
  .github/actions/calculate-next-internal-version/next-prerelease.sh
  .github/actions/git-check-existing-tag/action.yml
  .github/actions/git-latest-tag/action.yml
  .github/actions/helm-package-chart/action.yml
  .github/actions/helm-parse-next-release/action.yml
  .github/actions/load-release-descriptor/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/nexus-create-staging/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/resolve-preview-name/resolve-preview-name.sh
  .github/actions/send-slack-notification/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
Labels: PR: partially-approved

#153 OPSEXP-1782 Fixup release script with more specific sed command
  release.sh
Labels: PR: reviewed-approved

#150 OPSEXP-1783 get-branch-name with sanitize and max length parameters
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/get-branch-name/action.yml
  .github/actions/get-branch-name/get-branch-name.sh
  .github/actions/get-branch-name/tests/get-branch-name.bats
  .github/workflows/test-with-bats.yml
  .github/workflows/test.yml
Labels: PR: partially-approved

#152 fix(AAE-10543): add validate-maven-versions Github action
  .github/actions/validate-maven-versions/action.yml
  README.md
Labels: PR: partially-approved

#156 Move readme under docs folder
  docs/README.md
Labels: PR: partially-approved

#158 fix(jx-updatebot-pr): update release binary version to 0.3.13
  .github/actions/jx-updatebot-pr/action.yml
Labels: PR: partially-approved

#159 Release v1.19.1
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#160 OPSEXP-1806 Fixup slack notification
  .github/actions/send-slack-notification/action.yml
Labels: PR: unreviewed

#161 Release v1.19.2
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#162 OPSEXP-1806 Fix multiline/markdown support in slack notification
  .github/actions/send-slack-notification/action.yml
  .github/actions/send-slack-notification/compute-message.sh
  .github/actions/send-slack-notification/tests/send-slack-notification.bats
  .github/workflows/test.yml
Labels: PR: reviewed-approved
