Repository Alfresco/alfresco-build-tools, pull requests merged in 2022-12, with the labels that each got.

#190 AAE-11403: improve pre-commit actions doc in README
  docs/README.md
Labels: PR: partially-approved

#194 AAE-11373 add possibility to skip docker build
  .github/actions/maven-build-and-tag/action.yml
Labels: PR: partially-approved

#195 Release v1.24.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#196 AAE-11711: Improve slack notification payload
  .github/actions/send-slack-notification/action.yml
  .github/actions/send-slack-notification/compute-message.sh
  .github/actions/send-slack-notification/tests/send-slack-notification.bats
Labels: PR: partially-approved

#197 Release v1.24.1
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#192 OPSEXP-1802 Pre-Commit Hooks Best Practices in Build Tools
  docs/pre-commit-hooks.md
Labels: PR: reviewed-approved

#198 AAE-11711: add text on slack notif payload
  .github/actions/send-slack-notification/action.yml
Labels: PR: partially-approved

#199 Release v1.24.2
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#189 ACS-3844 Add setup-java-build action for standard setup of Java/Maven
  .github/actions/setup-java-build/action.yml
  docs/README.md
Labels: PR: partially-approved

#203 OPSEXP-1584: use new values for persistence
  .github/actions/dbp-charts/verify-helm/helm_install.sh
Labels: PR: partially-approved

#200 AAE-11722 ease up reportportal integration
  .github/actions/reportportal-prepare/action.yml
  .github/actions/reportportal-prepare/get-rp-input.sh
  .github/actions/reportportal-prepare/tests/reportportal-prepare.bats
  .github/actions/reportportal-summarize/action.yml
  .github/actions/reportportal-summarize/get-rp-output.sh
  .github/actions/reportportal-summarize/get-slack-message.sh
  .github/actions/reportportal-summarize/tests/empty-launch.json
  .github/actions/reportportal-summarize/tests/get-rp-output.bats
  .github/actions/reportportal-summarize/tests/get-slack-message.bats
  .github/actions/reportportal-summarize/tests/sample-launch.json
  .github/actions/reportportal-summarize/tests/sample-launches.json
  .github/actions/reportportal-summarize/tests/write-step-summary.bats
  .github/actions/reportportal-summarize/write-step-summary.sh
  .github/actions/send-slack-notification/action.yml
  .github/actions/send-slack-notification/compute-message.sh
  .github/actions/send-slack-notification/tests/send-slack-notification.bats
  .github/workflows/test.yml
  docs/README.md
  docs/images/rp-gh-summary.png
  docs/images/rp-sample.png
  docs/images/send-slack-custom-message.png
  docs/images/send-slack-pr.png
  docs/images/send-slack-push.png
Labels: PR: partially-approved

#201 AAE-11760 git-latest-tag-sha action
  .github/actions/git-latest-tag/action.yml
  .github/actions/git-latest-tag/git-latest-tag.sh
  .github/actions/git-latest-tag/tests/git-latest-tag.bats
  docs/README.md
Labels: PR: unreviewed

#206 fix(load-release-descriptor): add notes-start-tag parameter
  .github/actions/load-release-descriptor/action.yml
Labels: PR: partially-approved

#207 Release v1.27.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved
