Repository Alfresco/alfresco-build-tools, pull requests merged in 2023-02, with the labels that each got.

#228 ACS-4456 Generalize reusable workflow for Maven build and release
  .github/workflows/build-and-release-maven.yml
Labels: PR: unreviewed

#225 ACS-4456 Add reusable workflow for basic Maven build and release
  .github/workflows/build-and-release-maven.yml
Labels: PR: partially-approved

#229 Release v1.34.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-release-maven.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: unreviewed

#230 ACS-4456 Fix private repository releases with reusable workflow
  .github/workflows/build-and-release-maven.yml
Labels: PR: partially-approved

#231 Release v1.34.1
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-release-maven.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#232 ACS-3750 Use correct Git token for reusable workflow releases
  .github/workflows/build-and-release-maven.yml
Labels: PR: partially-approved

#233 Release v1.34.2
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-release-maven.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#215 [AAE-11861] add 'Create preview' feature
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-update-pom-version/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  docs/README.md
Labels: enhancement, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#236 Release v1.35.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-release-maven.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#237 ACS-4506 Fix build-and-release-maven workflow DependaBot PRs
  .github/workflows/build-and-release-maven.yml
Labels: PR: partially-approved

#238 Release v1.35.1
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-release-maven.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#239 OPSEXP-2004 Add auto-commit support for pre-commit action
  .github/actions/pre-commit/action.yml
  docs/README.md
Labels: PR: partially-approved

#240 Action for freeing runner's disk space
  .github/actions/free-hosted-runner-disk-space/action.yml
  .github/workflows/test.yml
  docs/README.md
Labels: PR: reviewed-approved

#241 Release v1.35.2
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-release-maven.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#242 Hint in the docs that pre-commit auto-commit requires permissions
  docs/README.md
Labels: PR: reviewed-approved
