Repository Alfresco/alfresco-build-tools, pull requests merged in 2023-01, with the labels that each got.

#208 ACS-4245 Add 'global' option for configure-git-author action
  .github/actions/configure-git-author/action.yml
  docs/README.md
Labels: PR: partially-approved

#209 Document procedure to retrieve travis secure envs on public repos
  docs/travis.md
Labels: PR: reviewed-approved

#210 OPSEXP-1761: use per-LB sg annotation (-extra-security-groups)
  .github/actions/dbp-charts/verify-helm/helm_install.sh
Labels: PR: partially-approved

#213 Release v1.28.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: unreviewed

#211 AAE-7305 add action to auto promote Nexus staging repository
  .github/actions/nexus-close-staging/action.yml
  .github/actions/nexus-close-staging/close-payload-template.json
  .github/actions/nexus-create-staging/action.yml
  .github/actions/nexus-release-staging/action.yml
  .github/actions/nexus-release-staging/promote-payload-template.json
  docs/README.md
Labels: PR: partially-approved

#214 Release v1.29.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#216 ACS-3844 Contribute get-build-info to alfresco-build-tools
  .github/actions/get-build-info/action.yml
  docs/README.md
Labels: PR: partially-approved

#217 Release v1.30.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: reviewed-approved

#218 Update snippet in configure-git-author to use the new vars GH feature
  docs/README.md
Labels: PR: partially-approved

#219 Fix long sha value output in git-latest-tag
  .github/actions/git-latest-tag/action.yml
Labels: PR: reviewed-approved

#220 OPSEXP-1942 Add action to yamllint rendered helm templates
  .github/actions/helm-template-yamllint/.yamllint.yml
  .github/actions/helm-template-yamllint/action.yml
  .github/actions/helm-unit-tests/action.yml
  docs/README.md
Labels: PR: unreviewed

#221 Release v1.31.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#222 AAE-12308: fix slack notification when commit message contains CTLR-M…
  .github/actions/send-slack-notification/compute-message.sh
  .github/actions/send-slack-notification/tests/sample-commit-message.txt
  .github/actions/send-slack-notification/tests/send-slack-notification.bats
  .pre-commit-config.yaml
Labels: PR: partially-approved

#223 ACS-3750 Set default veracode-fails-build to 'true'
  .github/actions/veracode/action.yml
  .github/actions/veracode/source_clear.sh
  docs/README.md
Labels: PR: partially-approved

#224 Release v1.32.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved

#226 ACS-4455 Install custom settings.xml as part of setup-java-build
  .github/actions/setup-java-build/action.yml
  docs/README.md
Labels: PR: partially-approved

#227 Release v1.33.0
  .github/actions/build-helm-chart/action.yml
  .github/actions/calculate-next-internal-version/action.yml
  .github/actions/dbp-charts/publish-chart/action.yml
  .github/actions/dbp-charts/verify-helm/action.yml
  .github/actions/get-build-info/action.yml
  .github/actions/helm-integration-tests/action.yml
  .github/actions/helm-publish-chart/action.yml
  .github/actions/helm-release-and-publish/action.yml
  .github/actions/helm-update-chart-version/action.yml
  .github/actions/maven-build-and-tag/action.yml
  .github/actions/maven-release/action.yml
  .github/actions/publish-helm-chart/action.yml
  .github/actions/send-slack-notification/action.yml
  .github/actions/setup-helm-docs/action.yml
  .github/actions/setup-jx-release-version/action.yml
  .github/actions/setup-terraform-docs/action.yml
  .github/actions/update-pom-to-next-pre-release/action.yml
  .github/workflows/build-and-tag-maven.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/helm-publish-new-package-version.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.aws-iam-authenticator_install.yml
  .travis.helm-docs_install.yml
  .travis.helm.yml
  .travis.helm_install.yml
  .travis.java.yml
  .travis.java_docker.yml
  .travis.jq_install.yml
  .travis.kcadm_install.yml
  .travis.kubepug_install.yml
  .travis.kubernetes_install.yml
  .travis.rancher_cli_install.yml
  .travis.rancher_cli_kubernetes_config.yml
  .travis.terraform-docs_install.yml
  .travis.terraform_install.yml
  .travis.tflint_install.yml
  .travis.yq_install.yml
Labels: PR: partially-approved
